<?php
array("Agder",
    array("Arendal",
        "Birkenes",
        "Bygland",
        "Bykle",
        "Evje og Hornnes",
        "Farsund",
        "Flekkefjord",
        "Froland",
        "Gjerstad",
        "Grimstad",
        "Hægebostad",
        "Iveland",
        "Kristiansand",
        array("Kristiansand Nord",
            "Kristiansand Sentrum",
            "Kristiansand Vest",
            "Kristiansand Øst",
            "Songdalen",
            "Søgne",
        ), "Kvinesdal",
        "Lillesand",
        "Lindesnes",
        "Lyngdal",
        "Risør",
        "Sirdal",
        "Tvedestrand",
        "Valle",
        "Vegårshei",
        "Vennesla",
        "Åmli",
        "Åseral",
    ), "Innlandet",
    array("Alvdal",
        "Dovre",
        "Eidskog",
        "Elverum",
        "Engerdal",
        "Etnedal",
        "Folldal",
        "Gausdal",
        "Gjøvik",
        "Gran",
        "Grue",
        "Hamar",
        "Kongsvinger",
        "Lesja",
        "Lillehammer",
        "Lom",
        "Løten",
        "Nordre Land",
        "Nord-Aurdal",
        "Nord-Fron",
        "Nord-Odal",
        "Os (Innlandet)",
        "Rendalen",
        "Ringebu",
        "Ringsaker",
        "Sel",
        "Skjåk",
        "Stange",
        "Stor-Elvdal",
        "Søndre Land",
        "Sør-Aurdal",
        "Sør-Fron",
        "Sør-Odal",
        "Tolga",
        "Trysil",
        "Tynset",
        "Vang",
        "Vestre Slidre",
        "Vestre Toten",
        "Vågå",
        "Våler (Innlandet)",
        "Østre Toten",
        "Øyer",
        "Øystre Slidre",
        "Åmot",
        "Åsnes",
    ), "Møre og Romsdal",
    array("Aukra",
        "Aure",
        "Averøy",
        "Fjord",
        "Giske",
        "Gjemnes",
        "Hareid",
        "Herøy (M.R.)",
        "Hustadvika",
        "Kristiansund",
        "Molde",
        "Rauma",
        "Sande (M.R.)",
        "Smøla",
        "Stranda",
        "Sula",
        "Sunndal",
        "Surnadal",
        "Sykkylven",
        "Tingvoll",
        "Ulstein",
        "Vanylven",
        "Vestnes",
        "Volda",
        "Ørsta",
        "Ålesund",
    ), "Nordland",
    array("Alstahaug",
        "Andøy",
        "Beiarn",
        "Bindal",
        "Bodø",
        "Brønnøy",
        "Bø (Nordland)",
        "Dønna",
        "Evenes",
        "Fauske",
        "Flakstad",
        "Gildeskål",
        "Grane",
        "Hadsel",
        "Hamarøy",
        "Hattfjelldal",
        "Hemnes",
        "Herøy (Nordland)",
        "Leirfjord",
        "Lurøy",
        "Lødingen",
        "Meløy",
        "Moskenes",
        "Narvik",
        "Nesna",
        "Rana",
        "Rødøy",
        "Røst",
        "Saltdal",
        "Sortland",
        "Steigen",
        "Sømna",
        "Sørfold",
        "Træna",
        "Vefsn",
        "Vega",
        "Vestvågøy",
        "Vevelstad",
        "Værøy",
        "Vågan",
        "Øksnes",
    ), "Oslo",
    array("Bjerke",
        "Bygdøy - Frogner",
        "Bøler",
        "Ekeberg - Bekkelaget",
        "Furuset",
        "Gamle Oslo",
        "Grefsen - Kjelsås",
        "Grorud",
        "Grünerløkka - Sofienberg",
        "Hellerud",
        "Helsfyr - Sinsen",
        "Lambertseter",
        "Manglerud",
        "Nordstrand",
        "Romsås",
        "Røa",
        "Sagene - Torshov",
        "Sentrum",
        "Sogn",
        "Stovner",
        "St.Hanshaugen - Ullevål",
        "Søndre Nordstrand",
        "Ullern",
        "Uranienborg - Majorstuen",
        "Vinderen",
        "Østensjø",
    ), "Rogaland",
    array("Bjerkreim",
        "Bokn",
        "Eigersund",
        "Gjesdal",
        "Haugesund",
        "Hjelmeland",
        "Hå",
        "Karmøy",
        "Klepp",
        "Kvitsøy",
        "Lund",
        "Randaberg",
        "Sandnes",
        "Sauda",
        "Sokndal",
        "Sola",
        "Stavanger",
        array("Bjergsted/Byhaugen/ Kalh/Kampen",
            "Byøyer",
            "Eiganes/Stokka/Sandal",
            "Finnøy",
            "Forus/Godeset",
            "Gausel",
            "Hinna",
            "Hundvåg/Byøyer",
            "Kvernevik",
            "Madlamark/Gosen/Granneslia",
            "Madlasandnes/Hafrsfjord/Sunde",
            "Rennesøy",
            "Stavanger Sentrum/Vestre platå",
            "Stavanger Øst",
            "Storhaug vest",
            "Tasta/Vardenes/ Dusavik",
            "Tjensvoll/Ullandhaug",
            "Vaulen",
            "Våland/Bekkefaret",
            "Åsen/Hillevåg/Auglend",
        ), "Strand",
        "Suldal",
        "Time",
        "Tysvær",
        "Utsira",
        "Vindafjord",
    ), "Svalbard",
    "Troms og Finnmark",
    array("Alta",
        "Balsfjord",
        "Bardu",
        "Båtsfjord",
        "Dyrøy",
        "Gamvik",
        "Gratangen",
        "Hammerfest",
        "Harstad",
        "Hasvik",
        "Ibestad",
        "Karasjok",
        "Karlsøy",
        "Kautokeino",
        "Kvæfjord",
        "Kvænangen",
        "Kåfjord",
        "Lebesby",
        "Loppa",
        "Lyngen",
        "Målselv",
        "Måsøy",
        "Nesseby",
        "Nordkapp",
        "Nordreisa",
        "Porsanger",
        "Salangen",
        "Senja",
        "Skjervøy",
        "Storfjord",
        "Sørreisa",
        "Sør-Varanger",
        "Tana",
        "Tjeldsund",
        "Tromsø",
        array("Kvaløya",
            "Tromsdalen/Tomasjord/Kroken/Ramfjord",
            "Tromsøya, Midten",
            "Tromsøya, Nord",
            "Tromsøya, Sør",
        ), "Vadsø",
        "Vardø",
    ), "Trøndelag",
    array("Flatanger",
        "Frosta",
        "Frøya",
        "Grong",
        "Heim",
        "Hitra",
        "Holtålen",
        "Høylandet",
        "Inderøy",
        "Indre Fosen",
        "Levanger",
        "Lierne",
        "Malvik",
        "Melhus",
        "Meråker",
        "Midtre Gauldal",
        "Namsos",
        "Namsskogan",
        "Nærøysund",
        "Oppdal",
        "Orkland",
        "Osen",
        "Overhalla",
        "Rennebu",
        "Rindal",
        "Røros",
        "Røyrvik",
        "Selbu",
        "Skaun",
        "Snåsa",
        "Steinkjer",
        "Stjørdal",
        "Trondheim",
        array("Klæbu",
            "Trondheim Sentrum",
            "Trondheim Sør",
            "Trondheim Vest",
            "Trondheim Øst",
        ), "Tydal",
        "Verdal",
        "Ørland",
        "Åfjord",
    ), "Vestfold og Telemark",
    array("Bamble",
        "Drangedal",
        "Fyresdal",
        "Færder",
        "Hjartdal",
        "Holmestrand",
        "Horten",
        "Kragerø",
        "Kviteseid",
        "Larvik",
        "Midt-Telemark",
        "Nissedal",
        "Nome",
        "Notodden",
        "Porsgrunn",
        "Sandefjord",
        "Seljord",
        "Siljan",
        "Skien",
        "Tinn",
        "Tokke",
        "Tønsberg",
        "Vinje",
    ), "Vestland",
    array("Alver",
        "Askvoll",
        "Askøy",
        "Aurland",
        "Austevoll",
        "Austrheim",
        "Bergen",
        array("Arna",
            "Bergen Sentrum",
            "Bergen Vest",
            "Fana",
            "Fyllingsdalen",
            "Landås",
            "Åsane",
        ), "Bjørnafjorden",
        "Bremanger",
        "Bømlo",
        "Eidfjord",
        "Etne",
        "Fedje",
        "Fitjar",
        "Fjaler",
        "Gloppen",
        "Gulen",
        "Hyllestad",
        "Høyanger",
        "Kinn",
        "Kvam",
        "Kvinnherad",
        "Luster",
        "Lærdal",
        "Masfjorden",
        "Modalen",
        "Osterøy",
        "Samnanger",
        "Sogndal",
        "Stad",
        "Stord",
        "Stryn",
        "Sunnfjord",
        "Sveio",
        "Tysnes",
        "Ullensvang",
        "Ulvik",
        "Vaksdal",
        "Vik",
        "Voss",
        "Øygarden",
        "Årdal",
    ), "Viken",
    array("Aremark",
        "Asker",
        "Aurskog-Høland",
        "Bærum",
        "Drammen",
        "Eidsvoll",
        "Enebakk",
        "Flesberg",
        "Flå",
        "Fredrikstad",
        "Frogn",
        "Gjerdrum",
        "Gol",
        "Halden",
        "Hemsedal",
        "Hol",
        "Hole",
        "Hurdal",
        "Hvaler",
        "Indre Østfold",
        "Jevnaker",
        "Kongsberg",
        "Krødsherad",
        "Lier",
        "Lillestrøm",
        "Lunner",
        "Lørenskog",
        "Marker",
        "Modum",
        "Moss",
        "Nannestad",
        "Nes",
        "Nesbyen",
        "Nesodden",
        "Nittedal",
        "Nordre Follo",
        "Nore og Uvdal",
        "Rakkestad",
        "Ringerike",
        "Rollag",
        "Rælingen",
        "Råde",
        "Sarpsborg",
        "Sigdal",
        "Skiptvet",
        "Ullensaker",
        "Vestby",
        "Våler (Viken)",
        "Øvre Eiker",
        "Ål",
        "Ås",
    ),); ?>
